"""The first migration: every table 8.4 to 8.7 declared, and nothing else.

Revision ID: acf710336f5f
Revises: 
Create Date: 2026-10-01 10:25:04.520448

:returns: nothing; ``upgrade`` creates the schema and ``downgrade`` drops it
    again, so ``upgrade head`` then ``downgrade base`` returns an empty
    database.

Generated by ``alembic revision --autogenerate`` against
:data:`app.storage.models.Base.metadata`, so the three tables and their
columns are the models rather than a hand-copy of them.  The index pair is
8.7's and is written here by name because 8.7's ``index=True`` is a claim
about the mapping: SQLite keeps an index outside ``CREATE TABLE``, so this
file's ``create_index`` calls are what put the two in the database.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acf710336f5f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create the three tables and the two indexes on ``screenings``."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('screening_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(none_as_null=True), nullable=False),
    sa.Column('record_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_table('ledger_entries',
    sa.Column('sequence', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('merkle_root', sa.String(), nullable=False),
    sa.Column('signature', sa.String(), nullable=False),
    sa.Column('anchored_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('sequence', name=op.f('pk_ledger_entries'))
    )
    op.create_table('screenings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('score', sa.Double(), nullable=True),
    sa.Column('band', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('image_width', sa.Integer(), nullable=False),
    sa.Column('image_height', sa.Integer(), nullable=False),
    sa.Column('ruleset_version', sa.String(), nullable=True),
    sa.Column('model_versions', sa.JSON(), nullable=True),
    sa.Column('quality', sa.JSON(), nullable=True),
    sa.Column('flags', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_screenings'))
    )
    with op.batch_alter_table('screenings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screenings_band'), ['band'], unique=False)
        batch_op.create_index(batch_op.f('ix_screenings_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop the two indexes and the three tables, in that order."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screenings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screenings_created_at'))
        batch_op.drop_index(batch_op.f('ix_screenings_band'))

    op.drop_table('screenings')
    op.drop_table('ledger_entries')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
