"""10.2's two columns: the salt beside the digest, and the position in a batch.

Revision ID: b7d41c9e2f08
Revises: acf710336f5f
Create Date: 2026-10-01 14:02:11.904213

Adds ``record_salt`` and ``batch_index`` to ``audit_events``.  8.5's
migration pinned the table at eight columns; these are the two that let 9.17
recompute a row and rebuild its batch from the database rather than from
whatever a caller hands it (``D66``).

Both are nullable and no backfill is written.  ``batch_id`` is already
nullable for the same reason -- the batch stamps it later than the event --
and ``record_salt`` has to be, because a row written before this revision
carries no salt and a column a populated table cannot take is a limit on
deployment rather than a guarantee.  A row with no salt or no position is a
row 9.17 answers ``unknown`` for.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7d41c9e2f08'
down_revision: Union[str, Sequence[str], None] = 'acf710336f5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add the two columns 10.2's writer and 9.16's stamp write."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('record_salt', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('batch_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop the two columns again, in the reverse order."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_column('batch_index')
        batch_op.drop_column('record_salt')
    # ### end Alembic commands ###
