"""16.1's table: the group a traveler's documents are compared within.

Revision ID: be3f9e1a6e14
Revises: b7d41c9e2f08
Create Date: 2026-10-02 23:32:07.565090

Adds ``traveler_cases`` with exactly the three columns the task names --
``id``, ``created_at``, ``label`` -- and carries no index, because nothing
filters a case and ``id`` is the primary key.

Generated by ``alembic revision --autogenerate`` against
:data:`app.storage.models.Base.metadata` on a database already at head, so
the table is the model rather than a hand-copy of it (``D126``).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be3f9e1a6e14'
down_revision: Union[str, Sequence[str], None] = 'b7d41c9e2f08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create ``traveler_cases`` beside the three tables 8.4 to 8.6 made."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traveler_cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_traveler_cases'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop ``traveler_cases``, which nothing else references yet."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traveler_cases')
    # ### end Alembic commands ###
